### ISSUE TITLE
KeyError: gamesInSeries

### ISSUE THREAD

**Issue by suedunham** [kmac/mlbv#30] opened 2019-03-25 20:08 UTC
Things suddenly don't work today. I can't even get a listing with the bare 'mlbv' command. Here's the output.

```
Microsoft Windows [Version 10.0.17134.648]

$ mlbv
Traceback (most recent call last):
  File "C:\Users\Ed\AppData\Local\Programs\Python\Python37\Scripts\mlbv-script.py", line 11, in <module>
    load_entry_point('mlbv==0.0.8', 'console_scripts', 'mlbv')()
  File "c:\users\ed\appdata\local\programs\python\python37\lib\site-packages\mlbam\mlbv.py", line 194, in main
    game_day_tuple_list = gamedata_parser.process_game_data(args.date, args.days)
  File "c:\users\ed\appdata\local\programs\python\python37\lib\site-packages\mlbam\gamedata.py", line 263, in process_game_data
    game_records = self._get_games_by_date(game_date)
  File "c:\users\ed\appdata\local\programs\python\python37\lib\site-packages\mlbam\gamedata.py", line 141, in _get_games_by_date
    game_rec['gamesInSeries'] = str(game['gamesInSeries'])
KeyError: 'gamesInSeries'
```
New broadcast tweaks with the new season?

**Comment by kmac** [comment] 2019-03-25 20:10
Confirmed. I'll take a look tonight to see what has changed. Hopefully a minor tweak but who knows.

**Comment by kmac** [comment] 2019-03-25 20:51
@suedunham I've pushed a fix for this. It seems to be an anomaly for today's game only. I will include the fix in the next release. If you want to watch today's games maybe just grab the mlbam/gamedata.py file from here and copy it into your 'c:\users\ed\appdata\local\programs\python\python37\lib\site-packages\mlbam\gamedata.py' location. Just in case that doesn't work, I would backup the current gamedata.py file somewhere as well.

**Closed** 2019-08-28 21:39 UTC
